name: t_store
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  #utility packages
  http: ^1.0.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

#  State management
  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_core: ^2.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/products/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_methods/


  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
